POST http://localhost:4002/products
Content-Type: application/json

{
   "name": "Caneta lilás",
   "price": 3
}

###

POST http://localhost:4002/products
Content-Type: application/json

{
   "name": "Caderno 96 folhas",
   "price": 36.90
}

###

GET http://localhost:4002/products